// CREATE A NEW USER
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "firstname": "Yusuf",
    "lastname": "Falade",
    "email": "faladeyusuf54@email.com",
    "password": "Adetomi.54"
}