// DELETE OWN ACCOUNT (SIGNED IN USER)
DELETE http://localhost:5000/api/v1/users/me/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMjA3NTA5NC0xZWIxLTQ5ZDYtODgzNC1jM2E5MjY4N2Q0MjciLCJyb2xlIjoidXNlciIsImVtYWlsIjoiZmFsYWRleXVzdWY1NEBnbWFpbC5jb20iLCJpYXQiOjE3NjE1NDAyMTAsImV4cCI6MTc2MTYyNjYxMH0.ZddQFc_6uhQKhkKcRpmRu1GfSzipOZB5wsEe7qo7K0k

// DELETE ANY SINGLE USER (ADMIN)
DELETE http://localhost:5000/api/v1/users/b2075094-1eb1-49d6-8834-c3a92687d427
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMjA3NTA5NC0xZWIxLTQ5ZDYtODgzNC1jM2E5MjY4N2Q0MjciLCJyb2xlIjoidXNlciIsImVtYWlsIjoiZmFsYWRleXVzdWY1NEBnbWFpbC5jb20iLCJpYXQiOjE3NjE1NDAyMTAsImV4cCI6MTc2MTYyNjYxMH0.ZddQFc_6uhQKhkKcRpmRu1GfSzipOZB5wsEe7qo7K0k