// GET USER OWN PROFILE - USER
GET http://localhost:5000/api/v1/users/me
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYWU4YWFlNS0zMDY2LTQ1ZTktODk2ZC02NzU1ZjE2YzIwZDIiLCJyb2xlIjoidXNlciIsImVtYWlsIjoiZmFsYWRleXVzdWY1NEBnbWFpbC5jb20iLCJpYXQiOjE3NjE4MTQyNTgsImV4cCI6MTc2MTkwMDY1OH0.Twlt8a7EXHKp2X92nCw93o6QVSQGUk42GkZl9lEupmw 

// GET ALL USERS - ADMIN ONLY
GET http://localhost:5000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNDYxMzgxNS0yYWEwLTQwOGYtODczMy1iNmZhM2MyOWRiYTgiLCJyb2xlIjoidXNlciIsImVtYWlsIjoiZmFsYWRleXVzdWY1NEBnbWFpbC5jb20iLCJpYXQiOjE3NjE2MTc5NDIsImV4cCI6MTc2MTcwNDM0Mn0.OQYSp8jTlbDv2ULxLFBsor17izF1J0n64aXHfN4oSNo

// GET SINGLE USER - ADMIN
GET http://localhost:5000/api/v1/users/f4613815-2aa0-408f-8733-b6fa3c29dba8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNDYxMzgxNS0yYWEwLTQwOGYtODczMy1iNmZhM2MyOWRiYTgiLCJyb2xlIjoidXNlciIsImVtYWlsIjoiZmFsYWRleXVzdWY1NEBnbWFpbC5jb20iLCJpYXQiOjE3NjE2MTc5NDIsImV4cCI6MTc2MTcwNDM0Mn0.OQYSp8jTlbDv2ULxLFBsor17izF1J0n64aXHfN4oSNo
