// GET ALL USERS - ADMIN ONLY
GET http://localhost:5000/api/v1/users
Cookie: authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNzg1M2IwYS0xYjU0LTQ0NTgtYWI1Yy05NzZmNWQ5YmUzYmEiLCJpYXQiOjE3NTg0MjEyODgsImV4cCI6MTc1ODUwNzY4OH0.cCMvbhQDmqOIk0p8o3tEzahUPl1xvIDC-XvD8syeIwU