// EXPORT USER DATA
POST http://localhost:5000/api/v1/users/export-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMzU4NmYyNC04Mjk2LTQyN2MtOWM5ZC00NThmZWEzY2Q4NmIiLCJyb2xlIjoidXNlciIsImVtYWlsIjoiZmFsYWRleXVzdWY1NEBnbWFpbC5jb20iLCJpYXQiOjE3NjE2NTM0NzQsImV4cCI6MTc2MTczOTg3NH0.NBXkO9tScGGkZzMrWUoVGmteQESj7Byp7jcUM3R4U24

// SUSPEND USER - ADMIN
POST http://localhost:5000/api/v1/users/2f0efdd1-c532-4647-9ce4-31a80ebf147f/suspend
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NmE1MDQ2MC0yZjVkLTQxZmEtYTM3NC1mNjQ4YzcwMTViOWUiLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImZhbGFkZXl1c3VmNTRAZ21haWwuY29tIiwiaWF0IjoxNzYyMzQyMTg2LCJleHAiOjE3NjI0Mjg1ODZ9.P2chO9BnPmodTkwna9aPmLIpxHUpxgqtrgj65N8G9lc

// ACTIVATE USER - ADMIN
POST http://localhost:5000/api/v1/users/2f0efdd1-c532-4647-9ce4-31a80ebf147f/activate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NmE1MDQ2MC0yZjVkLTQxZmEtYTM3NC1mNjQ4YzcwMTViOWUiLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImZhbGFkZXl1c3VmNTRAZ21haWwuY29tIiwiaWF0IjoxNzYyMzQyMTg2LCJleHAiOjE3NjI0Mjg1ODZ9.P2chO9BnPmodTkwna9aPmLIpxHUpxgqtrgj65N8G9lc