// EXPORT USER DATA
POST http://localhost:5000/api/v1/users/export-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMzU4NmYyNC04Mjk2LTQyN2MtOWM5ZC00NThmZWEzY2Q4NmIiLCJyb2xlIjoidXNlciIsImVtYWlsIjoiZmFsYWRleXVzdWY1NEBnbWFpbC5jb20iLCJpYXQiOjE3NjE2NTM0NzQsImV4cCI6MTc2MTczOTg3NH0.NBXkO9tScGGkZzMrWUoVGmteQESj7Byp7jcUM3R4U24